### ISSUE TITLE
UI - Notification icon (beside the User Profile tab)

### ISSUE THREAD

**Issue by alvincrisuycorel** [HP-Corel/AttendanceTracker#34] opened 2015-07-01 23:48 UTC

**Comment by asjr4584** [comment] 2015-07-02 03:35
Assigning this to Jin.

**Comment by Jinsuke** [comment] 2015-07-02 06:30
Added Notification icon near User Profile dropdown.
--
- Added **Notifications Page** under **profile/notifications**
- **Notification Page** content is to be discussed.

![image](https://cloud.githubusercontent.com/assets/10201846/8471039/6de1f696-20c6-11e5-97a4-d9c6dcbad353.png)

Site: http://16.178.42.203/profile/notifications
-

**Comment by gigiadamantopoulos** [comment] 2015-07-02 16:56
No issues

**Comment by asjr4584** [comment] 2015-07-03 02:57
@alvincrisuycorel @gigiadamantopoulos is that the final icon for notification? Do you have alternate colors for for new notifications and no notifications?

**Comment by Jinsuke** [comment] 2015-07-03 05:22
Changes
-
Icon has been changed to bell. It will turn red once a notification has been received.

![image](https://cloud.githubusercontent.com/assets/10201846/8493039/9017b302-2186-11e5-8b3f-cea31ed7f1c7.png)

**Comment by asjr4584** [comment] 2015-07-03 05:25
@gigiadamantopoulos for testing, please.

**Comment by gigiadamantopoulos** [comment] 2015-07-03 19:04
Size of the notification changes when you navigate other pages:

Dashboard:
![image](https://cloud.githubusercontent.com/assets/10202106/8503902/53365a06-21f9-11e5-8399-7c1e4040a705.png)

Members:
![image](https://cloud.githubusercontent.com/assets/10202106/8503906/5f6cfd0c-21f9-11e5-9da0-7fec34a95109.png)

**Comment by Jinsuke** [comment] 2015-07-05 23:09
Hi @gigiadamantopoulos ,
I'm not sure what you mean about this, they are only using one default header so all changes on the header should reflect on all pages. Can you please check again? :smile:

**Comment by gigiadamantopoulos** [comment] 2015-07-07 16:29
Hi Kuya @Jinsuke , as discussed earlier... it's still the same..

**Comment by Jinsuke** [comment] 2015-07-09 04:47
Hi @gigiadamantopoulos , I have consulted this to @alvincrisuycorel and it seems that this maybe caused by the scrollbar on certain pages. This works fine. :grin:

**Comment by gigiadamantopoulos** [comment] 2015-07-09 16:34
Thanks!

**Comment by chrisperez** [comment] 2015-07-15 02:16
Added new feature.
---

When there are unread messages, the count will appear next to the bell icon and the bell icon will turn red.

![image](https://cloud.githubusercontent.com/assets/4833394/8689287/2a2c3fee-2ad8-11e5-92be-ea05c5a63643.png)

**Comment by lyn2711** [comment] 2015-07-23 07:16
Suggestion:

When there are no notifications, when you hover your mouse over the icon, a message "No new notifications" will appear

**Comment by chrisperez** [comment] 2015-07-27 00:54
Done

- When there are unread messages

![image](https://cloud.githubusercontent.com/assets/4833394/8896906/cf58a616-343c-11e5-9779-a766e6e6be3f.png)

- When there are NO unread messages

![image](https://cloud.githubusercontent.com/assets/4833394/8896911/f5b19e76-343c-11e5-960f-50815a69c18d.png)

**Comment by lyn2711** [comment] 2015-07-30 11:38
Can we show the latest date on top of the list of notifications?  Can we show the New notifications in bold letters or a way make it more prominent than the Old notifications?

**Comment by chrisperez** [comment] 2015-07-31 03:12
The Unread are now on top and sorted according to the latest date. Please test.

**Comment by gigiadamantopoulos** [comment] 2015-08-04 06:51
Passed for the icon... but the notif page is not... @alvincrisuycorel 

![image](https://cloud.githubusercontent.com/assets/10202106/9054885/3ecf2e8a-3ab8-11e5-8203-e63e77408dad.png)

**Comment by lyn2711** [comment] 2015-08-14 12:43
Pass, test done on 203

**Comment by gigiadamantopoulos** [comment] 2015-09-04 00:47
passed in 201

**Comment by gigiadamantopoulos** [comment] 2015-09-04 04:52
Additional feature as suggested:

1. Add a Search function in the Notification Page
2. Add a pagination.

**Comment by Jinsuke** [comment] 2015-09-04 05:43
Updated
-
- **Added Search Filter**
![image](https://cloud.githubusercontent.com/assets/10201846/9677303/f1b291f8-530a-11e5-931e-1531a9c8c3d8.png)

**Comment by asjr4584** [comment] 2015-09-07 00:01
Deadline: September 11, 2015

**Comment by Jinsuke** [comment] 2015-09-07 06:54
Update
-
- Added Notification Search by Month and Filter
![image](https://cloud.githubusercontent.com/assets/10201846/9710768/47868fbe-5570-11e5-9b92-717a115fdbd4.png)

Done in my local pc. For Testing on local.
http://16.178.42.181/
-
**All Passwords are: 123**
- **Admin Account:** jin@gmail.com

- **Supervisor Account:** alvincris.uy@hpe.com

- **TL Account:**
  - Dev Team: alfredoa.salvadorjr@hp.com
  - Team Mark: marktristan.cruz@hpe.com

- **Agent Account:**
  - Dev Team:
    - christopher.perez@hpe.com
  - Team Mark:
    - reynan.fortes@hpe.com


**THANK YOU @alvincrisuycorel **

**Comment by lyn2711** [comment] 2015-09-07 07:35
Passed, test done in 181

**Comment by lyn2711** [comment] 2015-09-07 07:43
Pass, test done in 203

**Comment by lyn2711** [comment] 2015-09-07 07:49
Passed, test done in 203

**Closed by lyn2711** 2015-09-07 07:49 UTC
Labels: Medium
